version: '3.8'

services:
  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./app:/app

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: flaskdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
